import { Link } from 'react-router-dom';

export function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <h1 className="text-3xl font-bold text-slate-900">Privacy policy</h1>
      <p className="mt-2 text-sm text-slate-500">Last updated: September 2026</p>

      <section className="mt-8 space-y-6 text-slate-700">
        <div>
          <h2 className="text-xl font-bold text-slate-900">The short version</h2>
          <p className="mt-3 leading-relaxed">
            You can take every screening without an account. We store your answers so we can show
            you a result, but we do not tie them to your identity unless you choose to create an
            account. We do not sell your data, and we do not show advertising.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-bold text-slate-900">What we store</h2>
          <ul className="mt-3 list-disc space-y-2 pl-5 leading-relaxed">
            <li>
              <strong>Anonymous screenings:</strong> your answers, the screening you took, the date,
              and the result. These are linked to a random identifier (a UUID) generated by your
              browser and stored in local storage. It contains no information about you.
            </li>
            <li>
              <strong>Account screenings:</strong> if you create an account, we additionally store
              your email address and an optional display name, and link your results to that
              account.
            </li>
            <li>
              <strong>Technical data:</strong> standard server logs (IP address, request times) are
              collected for security and rate limiting, and are not linked to your results.
            </li>
          </ul>
        </div>

        <div>
          <h2 className="text-xl font-bold text-slate-900">What we do not do</h2>
          <ul className="mt-3 list-disc space-y-2 pl-5 leading-relaxed">
            <li>We do not sell, rent, or share your data with advertisers.</li>
            <li>We do not use your answers to train models or for research without a separate opt-in.</li>
            <li>We do not use third-party tracking, analytics beacons, or advertising cookies.</li>
            <li>We do not attempt to identify you from your answers.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-xl font-bold text-slate-900">How to delete your data</h2>
          <p className="mt-3 leading-relaxed">
            Clearing your browser's site data removes your anonymous identifier, which makes your
            stored results unreachable. To permanently delete an account and everything attached to
            it, contact us and we will remove it.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-bold text-slate-900">Not medical advice</h2>
          <p className="mt-3 leading-relaxed">
            MindCheck is a screening tool, not a medical service. It cannot diagnose a condition or
            provide treatment. If you are in crisis, please contact a crisis line or your local
            emergency number — see the{' '}
            <Link to="/resources" className="font-medium text-primary hover:underline">
              resources page
            </Link>
            .
          </p>
        </div>
      </section>
    </div>
  );
}
